/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SistGestViews;

import SistGestDao.AgendaDao;
import SistGestDao.ColaboradorDao;
import SistGestModelo.Agenda;
import SistGestModelo.Colaborador;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Aluno
 */
public class AgendaColaboradorADM extends javax.swing.JPanel {
    /**
     * Creates new form AgendaColaborador
     */
    public AgendaColaboradorADM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelEndereco = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        cpTitulo = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        cpDescricao = new javax.swing.JTextArea();
        lbAgendaColaborador = new javax.swing.JLabel();
        cpDataCria = new javax.swing.JFormattedTextField();
        labelDataCria = new javax.swing.JLabel();
        cpDataCompr = new javax.swing.JFormattedTextField();
        lbIDC = new javax.swing.JLabel();
        cpIdColab = new javax.swing.JTextField();
        lbIDE = new javax.swing.JLabel();
        cpEquipe = new javax.swing.JTextField();

        labelEndereco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelEndereco.setText("Data Compromisso:");

        btnSalvar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        cpTitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cpTitulo.setText("Digite o Título aqui...");

        cpDescricao.setColumns(20);
        cpDescricao.setRows(5);
        cpDescricao.setText("Dê uma descrição aqui...\n");
        jScrollPane2.setViewportView(cpDescricao);

        lbAgendaColaborador.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbAgendaColaborador.setText("Adcionar à Agenda de um Colaborador");

        try {
            cpDataCria.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-## ##:##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cpDataCria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpDataCriaActionPerformed(evt);
            }
        });

        labelDataCria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelDataCria.setText("Criada em:");

        try {
            cpDataCompr.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-## ##:##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lbIDC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbIDC.setText("Código do colaborador:");

        cpIdColab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpIdColabActionPerformed(evt);
            }
        });

        lbIDE.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbIDE.setText("Código da Equipe:");

        cpEquipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpEquipeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbAgendaColaborador))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1839, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelDataCria)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cpDataCria, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelEndereco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cpDataCompr, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(lbIDE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cpEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbIDC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cpTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cpIdColab, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(cpTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cpDataCompr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelEndereco)
                            .addComponent(labelDataCria)
                            .addComponent(cpDataCria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbIDE)
                            .addComponent(cpEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cpIdColab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbIDC)
                            .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lbAgendaColaborador)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 853, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        //vincula uma pagina 
        int idColabconv = Integer.parseInt(cpIdColab.getText());
        int idEquipe = Integer.parseInt(cpEquipe.getText());
        Agenda agenda = new Agenda();
        //puxa os dados do campo e seta em variaveis
        agenda.setDataCriacao(cpDataCria.getText());
        agenda.setDataCompromisso(cpDataCompr.getText());
        agenda.setTitulo(cpTitulo.getText());
        agenda.setDescricao(cpDescricao.getText());
        agenda.setColaborador_id(idColabconv);
        agenda.setEquipe_id(idEquipe);
              

        //Inserção do compromisso no DB
        AgendaDao agenDao = new AgendaDao();
        try {
            agenDao.inserir(agenda);
            JOptionPane.showMessageDialog(null, "Adcionado à sua Agenda com sucesso!");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Falha ao incerir em sua Agenda!");
            Logger.getLogger(CadastroColaborador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void cpDataCriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpDataCriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpDataCriaActionPerformed

    private void cpIdColabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpIdColabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpIdColabActionPerformed

    private void cpEquipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpEquipeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpEquipeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JFormattedTextField cpDataCompr;
    private javax.swing.JFormattedTextField cpDataCria;
    private javax.swing.JTextArea cpDescricao;
    private javax.swing.JTextField cpEquipe;
    private javax.swing.JTextField cpIdColab;
    private javax.swing.JTextField cpTitulo;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelDataCria;
    private javax.swing.JLabel labelEndereco;
    private javax.swing.JLabel lbAgendaColaborador;
    private javax.swing.JLabel lbIDC;
    private javax.swing.JLabel lbIDE;
    // End of variables declaration//GEN-END:variables
}
