/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SistGestViews;

import SistGestDao.AgendaDao;
import SistGestDao.ColaboradorDao;
import SistGestDao.EquipeDao;
import SistGestModelo.Colaborador;
import SistGestModelo.Equipe;
import java.awt.CardLayout;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.management.Query.eq;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aluno
 */
public class ListagemEquipe extends javax.swing.JPanel {
    //declaracao de variaveis privadas e do cardlayout
    private CardLayout cl;
    private int idEquipe;
        
    
    /**
     * Creates new form ListagemEquipe
     */
    public ListagemEquipe() {
        initComponents();
        //adicionado os paineis listagem e edicao
        this.add(painelListagem, "painelListagem");
        this.add(painelEdicao, "painelEdicao");

        
        this.cl = (CardLayout) this.getLayout();
        this.cl.show(this, "painelListagem");
    }
    
    private void popularTabela() {
        EquipeDao eqdao = new EquipeDao();
        List<Equipe> ListagemEquipe;

        try {
            ListagemEquipe = eqdao.listarEquipe();

            DefaultTableModel model = (DefaultTableModel) tblEquipe.getModel();
            List<Object> lista = new ArrayList<Object>();

            for (int i = 0; i < ListagemEquipe.size(); i++) {
                Equipe eq = ListagemEquipe.get(i);
                lista.add(new Object[]{eq.getId() ,eq.getNome(), eq.getDescricao()});
               

            }

            for (int idx = 0; idx < lista.size(); idx++) {
                model.addRow((Object[]) lista.get(idx));
            }

        } catch (SQLException ex) {
            String msg = "Ocorreu um erro ao obter as EQUIPES do banco de dados!";
            JOptionPane.showMessageDialog(null, msg);
            Logger.getLogger(ListagemColaboradores.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    
    private void preencherCamposEdicao(int idEquipe) throws SQLException {
        EquipeDao eqdao = new EquipeDao();
//(nome, descricao)
        
            Equipe equipe = eqdao.getEquipe(idEquipe);
            
            cpNomeEquipeEditar.setText(equipe.getNome());
            cpDescricaoEquipeEditar.setText(equipe.getDescricao());
            
    }
    
    private void limparTabela() {
        ((DefaultTableModel) tblEquipe.getModel()).setNumRows(0);
        tblEquipe.updateUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelListagem = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEquipe = new javax.swing.JTable();
        painelEdicao = new javax.swing.JPanel();
        btnEditarEquipe = new javax.swing.JButton();
        lbEditarEquipe = new javax.swing.JLabel();
        lbNomeEquipeEditar = new javax.swing.JLabel();
        cpNomeEquipeEditar = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        cpDescricaoEquipeEditar = new javax.swing.JTextArea();
        lbDescricaoEquipeEditar = new javax.swing.JLabel();
        btnEliminarEquipe = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        painelListagem.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                painelListagemComponentShown(evt);
            }
        });

        tblEquipe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_Equipe", "Nome", "Descrição"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblEquipe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEquipeMouseClicked(evt);
            }
        });
        tblEquipe.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tblEquipeComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(tblEquipe);

        javax.swing.GroupLayout painelListagemLayout = new javax.swing.GroupLayout(painelListagem);
        painelListagem.setLayout(painelListagemLayout);
        painelListagemLayout.setHorizontalGroup(
            painelListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(painelListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
        );
        painelListagemLayout.setVerticalGroup(
            painelListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(painelListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
        );

        add(painelListagem, "card2");

        btnEditarEquipe.setText("Salvar");
        btnEditarEquipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarEquipeActionPerformed(evt);
            }
        });

        lbEditarEquipe.setText("Editar Equipe");

        lbNomeEquipeEditar.setText("Nome:");

        cpNomeEquipeEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpNomeEquipeEditarActionPerformed(evt);
            }
        });

        cpDescricaoEquipeEditar.setColumns(20);
        cpDescricaoEquipeEditar.setRows(5);
        jScrollPane2.setViewportView(cpDescricaoEquipeEditar);

        lbDescricaoEquipeEditar.setText("Descricao da Equipe:");

        btnEliminarEquipe.setText("Eliminar");
        btnEliminarEquipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEquipeActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelEdicaoLayout = new javax.swing.GroupLayout(painelEdicao);
        painelEdicao.setLayout(painelEdicaoLayout);
        painelEdicaoLayout.setHorizontalGroup(
            painelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelEdicaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbEditarEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelEdicaoLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(painelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbDescricaoEquipeEditar)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelEdicaoLayout.createSequentialGroup()
                        .addComponent(lbNomeEquipeEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cpNomeEquipeEditar)))
                .addGap(58, 58, 58))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelEdicaoLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(btnEliminarEquipe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditarEquipe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addContainerGap())
        );
        painelEdicaoLayout.setVerticalGroup(
            painelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelEdicaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbEditarEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(painelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNomeEquipeEditar)
                    .addComponent(cpNomeEquipeEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(lbDescricaoEquipeEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(painelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditarEquipe)
                    .addComponent(btnEliminarEquipe)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        add(painelEdicao, "card3");
    }// </editor-fold>//GEN-END:initComponents

    private void tblEquipeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEquipeMouseClicked
       //quando pressionado em uma linha da tabela o painel edicao vem
       int linha = tblEquipe.getSelectedRow();

        if (linha != -1) {
            String codigo = tblEquipe.getValueAt(linha, 0).toString();
            int codigoEquipe = this.idEquipe = Integer.parseInt(codigo);
           try {
               this.preencherCamposEdicao(codigoEquipe);
           } catch (SQLException ex) {
               Logger.getLogger(ListagemEquipe.class.getName()).log(Level.SEVERE, null, ex);
           }
            this.cl.show(this, "painelEdicao");
        }
    }//GEN-LAST:event_tblEquipeMouseClicked

    private void tblEquipeComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tblEquipeComponentShown
        //Não Utiliza-se
    }//GEN-LAST:event_tblEquipeComponentShown

    private void painelListagemComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_painelListagemComponentShown
       //limpar e popular tabela 
        this.limparTabela();
        this.popularTabela();
    }//GEN-LAST:event_painelListagemComponentShown
    //metodo de editar tabela
    private void btnEditarEquipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarEquipeActionPerformed
        Equipe eq = new Equipe();
        
        eq.setId(this.idEquipe);
        eq.setNome(cpNomeEquipeEditar.getText());
        eq.setDescricao(cpDescricaoEquipeEditar.getText());

        //Inserção do colaborador no DB
        EquipeDao eqdao = new EquipeDao();
        try {
            eqdao.alterar(eq);
            JOptionPane.showMessageDialog(null, "EQUIPE alterado com sucesso!");
            this.cl.show(this, "painelListagem");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Falha ao alterar a EQUIPE!");
            this.cl.show(this, "painelListagem");
            Logger.getLogger(CadastroColaborador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEditarEquipeActionPerformed

    private void cpNomeEquipeEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpNomeEquipeEditarActionPerformed
        //CAMPO DE DIGITAÇÃO
    }//GEN-LAST:event_cpNomeEquipeEditarActionPerformed
    //metodo de eliminar equipe
    private void btnEliminarEquipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEquipeActionPerformed
        Object[] options = {"Sim", "Não"};
        int opcaoSelecionada = JOptionPane.showOptionDialog(null, "Deseja realmente eliminar esta EQUIPE ?", "Atenção!", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]);
     
        if (opcaoSelecionada == 0) {
            
            EquipeDao eqdao = new EquipeDao();
            
            try {
                eqdao.eliminar(this.idEquipe);              
                this.limparTabela();
                this.popularTabela();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "ELIMINE OS COLABORADORES DESTA EQUIPE ANTES!!");
                Logger.getLogger(ListagemColaboradores.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.cl.show(this, "painelListagem");
        }
    }//GEN-LAST:event_btnEliminarEquipeActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
       //quando botao cancelar pressionado volta para painel listagem
        this.cl.show(this, "painelListagem");
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditarEquipe;
    private javax.swing.JButton btnEliminarEquipe;
    private javax.swing.JTextArea cpDescricaoEquipeEditar;
    private javax.swing.JTextField cpNomeEquipeEditar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbDescricaoEquipeEditar;
    private javax.swing.JLabel lbEditarEquipe;
    private javax.swing.JLabel lbNomeEquipeEditar;
    private javax.swing.JPanel painelEdicao;
    private javax.swing.JPanel painelListagem;
    private javax.swing.JTable tblEquipe;
    // End of variables declaration//GEN-END:variables
}
