/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SistGestViews;

import SistGestDao.AgendaDao;
import SistGestModelo.Agenda;
import java.awt.CardLayout;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author slipk
 */
public class ListagemAgendaEquipe extends javax.swing.JPanel {
    private CardLayout cl;
    private int idAgendaEquipe;
    /**
     * Creates new form Agenda
     */
    public ListagemAgendaEquipe() {
        initComponents();

        
        this.add(ListagemAgendaEquipe, "painelListagemAgendaEquipe");
        this.add(PainelEdicao, "painelAgendaEdicao");
        
        this.cl = (CardLayout) this.getLayout();
        this.cl.show(this, "painelListagemAgendaEquipe");
    }
    
    private void popularTabela() {
        AgendaDao agendao = new AgendaDao();
        List<Agenda> Agenda;

        try {
            Agenda = agendao.listaCompromisso();

            DefaultTableModel model = (DefaultTableModel) tblAgendaEquipe.getModel();
            List<Object> lista = new ArrayList<Object>();
            //varre o banco de dados e seta a ordem que ira a parecer na tela 
            for (int i = 0; i < Agenda.size(); i++) {
                Agenda ag = Agenda.get(i);
                lista.add(new Object[]{ag.getIdAgenda(),ag.getDataCriacao(), ag.getDataCompromisso(), ag.getTitulo(),
                    ag.getDescricao(), ag.getEquipe_id()});
               
            }

            for (int idx = 0; idx < lista.size(); idx++) {
                model.addRow((Object[]) lista.get(idx));
            }

        } catch (SQLException ex) {
            String msg = "Erro ao obter dados!";
            JOptionPane.showMessageDialog(null, msg);
            Logger.getLogger(ListagemColaboradores.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    
    private void preencherCamposEdicao(int idAgendaEquipe) throws SQLException {
        AgendaDao agendao = new AgendaDao();

            Agenda agenda = agendao.getCompromisso(idAgendaEquipe);
            
            cpDataCriaEditar.setText(agenda.getDataCriacao());
            cpDataComprEditar.setText(agenda.getDataCompromisso());
            cpDescricaoEditar.setText(agenda.getDescricao());
            cpTituloEditar.setText(agenda.getTitulo());
    }
    
    private void limparTabela() {
        ((DefaultTableModel) tblAgendaEquipe.getModel()).setNumRows(0);
        tblAgendaEquipe.updateUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelEdicao = new javax.swing.JPanel();
        labelDataCriaEditar = new javax.swing.JLabel();
        cpDataCriaEditar = new javax.swing.JFormattedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        cpDescricaoEditar = new javax.swing.JTextArea();
        btnEliminarCompromisso = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        labelEnderecoEditar = new javax.swing.JLabel();
        cpDataComprEditar = new javax.swing.JFormattedTextField();
        cpTituloEditar = new javax.swing.JTextField();
        labelCadastroClienteEditar = new javax.swing.JLabel();
        ListagemAgendaEquipe = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAgendaEquipe = new javax.swing.JTable();

        setLayout(new java.awt.CardLayout());

        labelDataCriaEditar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelDataCriaEditar.setText("Criada em:");

        try {
            cpDataCriaEditar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-## ##:##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        cpDescricaoEditar.setColumns(20);
        cpDescricaoEditar.setRows(5);
        cpDescricaoEditar.setText("Dê uma descrição aqui...\n");
        jScrollPane2.setViewportView(cpDescricaoEditar);

        btnEliminarCompromisso.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEliminarCompromisso.setText("Eliminar");
        btnEliminarCompromisso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCompromissoActionPerformed(evt);
            }
        });

        btnEditar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        labelEnderecoEditar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelEnderecoEditar.setText("Data Compromisso:");

        try {
            cpDataComprEditar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-## ##:##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        cpTituloEditar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cpTituloEditar.setText("Digite o Título aqui...");

        labelCadastroClienteEditar.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        labelCadastroClienteEditar.setText("Editar Agenda da SUA Equipe");

        javax.swing.GroupLayout PainelEdicaoLayout = new javax.swing.GroupLayout(PainelEdicao);
        PainelEdicao.setLayout(PainelEdicaoLayout);
        PainelEdicaoLayout.setHorizontalGroup(
            PainelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelEdicaoLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(PainelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelEdicaoLayout.createSequentialGroup()
                        .addComponent(labelCadastroClienteEditar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PainelEdicaoLayout.createSequentialGroup()
                        .addGroup(PainelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2)
                            .addGroup(PainelEdicaoLayout.createSequentialGroup()
                                .addComponent(labelDataCriaEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cpDataCriaEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelEnderecoEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cpDataComprEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cpTituloEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminarCompromisso)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)))
                        .addGap(24, 24, 24))))
        );
        PainelEdicaoLayout.setVerticalGroup(
            PainelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelEdicaoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(labelCadastroClienteEditar)
                .addGap(49, 49, 49)
                .addGroup(PainelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpDataComprEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDataCriaEditar)
                    .addComponent(labelEnderecoEditar)
                    .addComponent(cpDataCriaEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpTituloEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarCompromisso)
                    .addComponent(btnEditar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addGap(51, 51, 51))
        );

        add(PainelEdicao, "card2");

        tblAgendaEquipe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id Agenda", "data da criação", "data do compromisso", "Tìtulo", "Descrição", "id da Equipe"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblAgendaEquipe.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tblAgendaEquipeComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(tblAgendaEquipe);

        javax.swing.GroupLayout ListagemAgendaEquipeLayout = new javax.swing.GroupLayout(ListagemAgendaEquipe);
        ListagemAgendaEquipe.setLayout(ListagemAgendaEquipeLayout);
        ListagemAgendaEquipeLayout.setHorizontalGroup(
            ListagemAgendaEquipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1920, Short.MAX_VALUE)
        );
        ListagemAgendaEquipeLayout.setVerticalGroup(
            ListagemAgendaEquipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
        );

        add(ListagemAgendaEquipe, "card3");
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarCompromissoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCompromissoActionPerformed
        Object[] options = {"Sim", "Não"};
        int opcaoSelecionada = JOptionPane.showOptionDialog(null, "Deseja realmente eliminar este compromisso ?", "Atenção!", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]);

        if (opcaoSelecionada == 0) {

            AgendaDao agendao = new AgendaDao();

            try {
                agendao.eliminar(idAgendaEquipe);
                this.limparTabela();
                this.popularTabela();
            } catch (SQLException ex) {
                Logger.getLogger(ListagemColaboradores.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.cl.show(this, "painelListagem");
        }
    }//GEN-LAST:event_btnEliminarCompromissoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        Agenda ag = new Agenda();

        ag.setIdAgenda(idAgendaEquipe);
        ag.setDataCriacao(cpDataCriaEditar.getText());
        ag.setDataCompromisso(cpDataComprEditar.getText());
        ag.setTitulo(cpTituloEditar.getText());
        ag.setDescricao(cpDescricaoEditar.getText());

        //Inserção do colaborador no DB
        AgendaDao agendao = new AgendaDao();
        try {
            agendao.alterar(ag);
            this.cl.show(this, "painelListagem");
            JOptionPane.showMessageDialog(null, "Agenda alterada com sucesso !");
        } catch (SQLException ex) {
            this.cl.show(this, "painelListagem");
            JOptionPane.showMessageDialog(null, "Falha ao alterar a Agenda !");
            Logger.getLogger(CadastroColaborador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void tblAgendaEquipeComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tblAgendaEquipeComponentShown
        this.limparTabela();
        this.popularTabela();        
    }//GEN-LAST:event_tblAgendaEquipeComponentShown


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ListagemAgendaEquipe;
    private javax.swing.JPanel PainelEdicao;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminarCompromisso;
    private javax.swing.JFormattedTextField cpDataComprEditar;
    private javax.swing.JFormattedTextField cpDataCriaEditar;
    private javax.swing.JTextArea cpDescricaoEditar;
    private javax.swing.JTextField cpTituloEditar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelCadastroClienteEditar;
    private javax.swing.JLabel labelDataCriaEditar;
    private javax.swing.JLabel labelEnderecoEditar;
    private javax.swing.JTable tblAgendaEquipe;
    // End of variables declaration//GEN-END:variables
}
